[build]
builder = "nixpacks"

[deploy]
startCommand = "cd commerce && python manage.py collectstatic --noinput && python manage.py migrate && gunicorn commerce.wsgi"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10